"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import Badge from "@atlaskit/badge";
import Button, { LoadingButton } from "@atlaskit/button";
import DynamicTable from "@atlaskit/dynamic-table";
import EmptyState from "@atlaskit/empty-state";
import Select from "@/components/apple-select";
import TextArea from "@atlaskit/textarea";
import { Box, Inline, Stack } from "@atlaskit/primitives";
import { PageHeading } from "@/components/page-heading";
import { SectionPanel } from "@/components/section-panel";
import { CandidateStatusLozenge } from "@/components/status-lozenge";
import { candidateTypeLabels } from "@/lib/labels";
import { useReydar } from "@/lib/store";
import type { CandidateStatus, CandidateType } from "@/lib/types";

const statusOptions = [
  "all",
  "mapped",
  "queued_for_approval",
  "safe_to_auto_engage",
  "monitor_only",
  "saved_as_insight",
  "blocked"
].map((value) => ({ label: value === "all" ? "All statuses" : value.replaceAll("_", " "), value }));

export function CandidateMapScreen() {
  const { activeProject, state, runDeliberationForCandidate } = useReydar();
  const [statusFilter, setStatusFilter] = useState<CandidateStatus | "all">("all");
  const [typeFilter, setTypeFilter] = useState<CandidateType | "all">("all");
  const [selectedId, setSelectedId] = useState<string | undefined>();
  const [runningId, setRunningId] = useState<string | null>(null);
  const candidates = state.conversationCandidates.filter((candidate) => candidate.projectId === activeProject.id);
  const filtered = useMemo(
    () =>
      candidates.filter((candidate) => {
        if (statusFilter !== "all" && candidate.status !== statusFilter) return false;
        if (typeFilter !== "all" && candidate.candidateType !== typeFilter) return false;
        return true;
      }),
    [candidates, statusFilter, typeFilter]
  );
  const selected = candidates.find((candidate) => candidate.id === selectedId) ?? filtered[0];
  const selectedItem = selected ? state.discoveredItems.find((item) => item.id === selected.discoveredItemId) : undefined;
  const typeOptions = [
    { label: "All candidate types", value: "all" },
    ...Object.entries(candidateTypeLabels).map(([value, label]) => ({ label, value }))
  ];

  const runDeliberation = async (candidateId: string) => {
    setRunningId(candidateId);
    await runDeliberationForCandidate(candidateId);
    setRunningId(null);
  };

  return (
    <>
      <PageHeading
        title="Candidate Map Debug"
        description="Admin fallback for inspecting mapped engagement points. The autonomous pipeline maps and deliberates candidates by default."
        breadcrumbs={[{ text: "ReydarOS", href: "/" }, { text: "Candidate Map Debug", href: "/candidates" }]}
        action={<Button appearance="primary" href="/signal-discovery">Run autonomous pipeline</Button>}
      />

      <div className="two-column-workspace">
        <Stack space="space.200">
          <SectionPanel
            className="filters-panel"
            title="Filters"
            description={`Showing ${filtered.length} candidate${filtered.length === 1 ? "" : "s"} for ${activeProject.name}.`}
          >
            <div className="filter-select-grid">
              <div className="form-field">
                <Select
                  isSearchable={false}
                  options={statusOptions}
                  value={statusOptions.find((option) => option.value === statusFilter)}
                  onChange={(option) => setStatusFilter(String(option?.value ?? "all") as CandidateStatus | "all")}
                />
              </div>
              <div className="form-field">
                <Select
                  isSearchable={false}
                  options={typeOptions}
                  value={typeOptions.find((option) => option.value === typeFilter)}
                  onChange={(option) => setTypeFilter(String(option?.value ?? "all") as CandidateType | "all")}
                />
              </div>
            </div>
          </SectionPanel>

          <SectionPanel title="Mapped candidates" description="Candidates are possible entry points generated by the pipeline before policy decisions are made.">
            {filtered.length ? (
              <DynamicTable
                head={{
                  cells: [
                    { key: "candidate", content: "Candidate" },
                    { key: "type", content: "Type" },
                    { key: "pain", content: "Pain point" },
                    { key: "intent", content: "Intent" },
                    { key: "relevance", content: "Relevance" },
                    { key: "risk", content: "Risk" },
                    { key: "status", content: "Status" },
                    { key: "action", content: "Actions" }
                  ]
                }}
                rows={filtered.map((candidate) => ({
                  key: candidate.id,
                  cells: [
                    {
                      key: "candidate",
                      content: (
                        <button className="link-button" onClick={() => setSelectedId(candidate.id)}>
                          {candidate.title}
                        </button>
                      )
                    },
                    { key: "type", content: candidateTypeLabels[candidate.candidateType] },
                    { key: "pain", content: candidate.detectedPainPoint },
                    { key: "intent", content: candidate.detectedIntent },
                    { key: "relevance", content: <Badge>{candidate.initialRelevanceScore}</Badge> },
                    { key: "risk", content: <Badge>{candidate.initialRiskScore}</Badge> },
                    { key: "status", content: <CandidateStatusLozenge value={candidate.status} /> },
                    {
                      key: "action",
                      content: (
                        <Inline space="space.050" shouldWrap>
                          <LoadingButton isLoading={runningId === candidate.id} onClick={() => runDeliberation(candidate.id)}>
                            Re-run decision
                          </LoadingButton>
                          <Button href={`/deliberation?candidate=${candidate.id}`}>Inspect trail</Button>
                        </Inline>
                      )
                    }
                  ]
                }))}
                rowsPerPage={10}
              />
            ) : (
              <EmptyState
                header="No candidates yet"
                description="Run the autonomous pipeline to map candidate entry points."
                primaryAction={<Button appearance="primary" href="/signal-discovery">Run autonomous pipeline</Button>}
              />
            )}
          </SectionPanel>
        </Stack>

        <aside className="right-panel-sticky">
          {selected ? (
            <Stack space="space.200">
              <SectionPanel title="Thread summary" description={`${selected.platform} / ${selected.community}`}>
                <Stack space="space.150">
                  <Inline space="space.100" shouldWrap>
                    <CandidateStatusLozenge value={selected.status} />
                    <Badge>{candidateTypeLabels[selected.candidateType]}</Badge>
                  </Inline>
                  <strong>{selected.title}</strong>
                  <p>{selected.candidateSummary}</p>
                  <TextArea value={selected.body} minimumRows={8} isReadOnly />
                  {selectedItem ? (
                    <span className="small-text muted-text">
                      Source score {selectedItem.score ?? "n/a"} · replies {selectedItem.replyCount ?? "n/a"}
                    </span>
                  ) : null}
                </Stack>
              </SectionPanel>
              <SectionPanel title="Recommended next step">
                <Stack space="space.150">
                  <p>{selected.recommendedNextStep}</p>
                  <p className="muted-text">{selected.whyWorthAnalyzing}</p>
                  <Inline space="space.100" shouldWrap>
                    <LoadingButton appearance="primary" isLoading={runningId === selected.id} onClick={() => runDeliberation(selected.id)}>
                      Re-run decision
                    </LoadingButton>
                    <Button href={`/deliberation?candidate=${selected.id}`}>Inspect decision trail</Button>
                    {selected.opportunityId ? <Button href={`/opportunities/${selected.opportunityId}`}>Open opportunity</Button> : null}
                  </Inline>
                  <Link href={selected.url}>Open source URL</Link>
                </Stack>
              </SectionPanel>
            </Stack>
          ) : (
            <SectionPanel title="No candidate selected">
              <p>Select a candidate to inspect the entry point and decision trail.</p>
            </SectionPanel>
          )}
        </aside>
      </div>

      <Box paddingBlockStart="space.200">
        <SectionPanel title="Mapping rules" description="The mapper identifies where ReydarOS could enter, not what it should say.">
          <div className="dense-grid">
            {["Original post", "Top comment", "Nested reply", "Unanswered question", "Competitor mention", "Tool request", "Buying intent", "Market insight only"].map((label) => (
              <div className="panel-muted" key={label}>
                <Box padding="space.150"><strong>{label}</strong></Box>
              </div>
            ))}
          </div>
        </SectionPanel>
      </Box>
    </>
  );
}
